# This is an example of a kvstore server configuration file

# Database Server configurations
[server]
addrs = ["tcp://127.0.0.1"]
port = 7275

[database]
path = "./dump.kvsdb"

# Logging configurations
[log]
# Log levels:
# - Debug   -> -1
# - Info    -> 0
# - Warn    -> 1
# - Error   -> 2
level = 0

# Path to save the log file
file_path = "/var/log/kvstore/kvstore-server.log"

# The maximum size of a log file in Megabytes before it gets rotated
max_size = 10

# The maximum amount of old log files to retain
max_backups = 6

# The maximum number of days to retain old log files based on the timestamp encoded in their filename
max_age = 28

# Determines if the rotated log files should be compressed using gzip
compress = true
