name: Lint

on:
  push:
    branches: [master, v*]
  pull_request:
    branches: [master, v*]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Run revive linter
        uses: docker://morphy/revive-action:v2
