name: Publish kvstore server image
on:
  push:
    branches: [master, v*]
    tags: ["v*"]

jobs:
  push_to_registry:
    name: Push kvstore server Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Run tests first
        run: go test -v ./...
      - name: Get tag
        if: contains(github.ref, 'refs/tags/')
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: hotpotatoc123/kvstore-server
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          push: true
          repository: hotpotatoc123/kvstore-server
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: "./build/kvstore-server/Dockerfile"
          build-args: |
            GIT_COMMIT=${{ env.GITHUB_SHA }}
            VERSION=${{ steps.tag.outputs.tag }}
